version: "3.7"

services:
  dynamodb:
    image: localstack/localstack
    container_name: dynamodb
    hostname: dynamodb
    ports:
      - "4569:4569"
      - "8080:8080"
    volumes:
      - ./:/app
      - ./scripts:/docker-entrypoint-initaws.d
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=sa-east-1
      - EDGE_PORT=4569
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
  dynamodb-admin:
    build:
      context: ./admin
    container_name: dynamodb-admin
    depends_on:
      - dynamodb
    ports:
      - "8001:8001"

networks:
  default:
    external: true
    name: ocr-network